SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_1](
	[aqwe] [nchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[bqwe] [nchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[cqwe] [nchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[dqwe] [nchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[dqwe] ASC,
	[cqwe] ASC,
	[bqwe] ASC,
	[aqwe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
